AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - "spec/rails_helper.rb"
    - "spec/dummy/**/*"

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false
