# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{autocomplete_for}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sean Kirby"]
  s.date = %q{2010-09-24}
  s.description = %q{Model-side logic for autocompleting belongs_to associations}
  s.email = %q{sskirby@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "autocomplete_for.gemspec",
     "lib/autocomplete_for.rb",
     "lib/autocomplete_for/autocomplete_for.rb",
     "rails/init.rb",
     "test/autocomplete_for_test.rb",
     "test/database.yml",
     "test/schema.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/sskirby/autocomplete_for}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{autocomplete_for}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Model-side logic for autocompleting belongs_to associations}
  s.test_files = [
    "test/schema.rb",
     "test/autocomplete_for_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, ["~> 2.3.4"])
      s.add_development_dependency(%q<pg>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, ["~> 2.3.4"])
      s.add_dependency(%q<pg>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, ["~> 2.3.4"])
    s.add_dependency(%q<pg>, [">= 0"])
  end
end

